name: Kong Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node-22.14.0-chrome-133.0.6943.126-1-ff-135.0.1-edge-133.0.3065.82-1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx cypress run

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: zf64811/zf64811.github.io
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/cypress/reports
