name: Kong Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  run-cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for Kong to be ready
        run: |
          echo "Waiting for Kong at http://localhost:8001 ..."
          for i in {1..15}; do
            if curl -s http://localhost:8001/status | grep -q '"database":{"reachable":true}'; then
              echo "Kong is ready!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 5
          done

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          command: npx cypress run --browser chrome

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.Kong_TOKEN }}
          external_repository: zf64811/Kong-cypress.github.io
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/cypress/reports
