name: Cypress Tests and Report

on:
  push:
    branches: [main] # 触发分支
  workflow_dispatch:

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 启动 Docker 环境
      - name: Start Docker containers
        run: |
          docker-compose up -d
          # 等待服务启动
          docker-compose run --rm kong-cp sh -c 'while ! curl -s http://localhost:8001/status >/dev/null; do sleep 5; done'

      # 安装依赖并运行 Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build # 如果有前端构建步骤
          start: docker-compose up -d # 确保服务运行
          wait-on: 'http://localhost:8001/status' # 等待 Kong 就绪

      # 部署报告到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KONG_TOKEN }}
          publish_dir: cypress/reports
          keep_files: false # 清理旧文件

      # 清理 Docker 环境
      - name: Stop containers
        if: always() # 即使测试失败也执行
        run: docker-compose down -v
