name: Cypress Tests and Report

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker containers
        run: |
          docker compose up -d
      - name: Wait for Kong
        run: |
          timeout 120 sh -c 'until curl -s http://localhost:8001/status >/dev/null; do sleep 5; echo "Waiting for Kong..."; done'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx cypress run

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.KONG_TOKEN }}
          external_repository: zf64811/Kong-cypress
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/cypress/reports
          keep_files: false 

      - name: Stop containers
        if: always() 
        run: docker compose down -v
